### ISSUE TITLE
能否拓展下滤镜功能？

### ISSUE THREAD

**Issue by MIkeeJY** [Skykai521/StickerCamera#3]
现有的貌似只有选择效果 没有 进度条去修改吧？

**Comment by MIkeeJY** [comment]
还有这个项目的BUG有点多，不经意就OOM 还有那个相机横向选图貌似也有问题

**Comment by Skykai521** [comment]
滤镜功能目前确实很弱，后面选择图片会添加旋转的功能，OOM的话，改掉过一些，我手头上的几个测试机都没有问题，能收集一下具体bug出现的位置吗？会着重修改崩溃的问题，谢啦！

**Comment by MIkeeJY** [comment]
就是图库浏览 还有 点击相机的那个横向的view 图片一点击就OOM  这个概率很高希望能再优化下
